// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmxsywgvzorrsxpfxhiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpteHN5d2d2em9ycnN4cGZ4aGl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDU5OTAsImV4cCI6MjA2NzE4MTk5MH0.NL-5lZrh4mTP8hRmfOP-Jg_vexMRCHtOZ6FwHhvQ6eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});